### PR TITLE
Fix 1 sftp

### LINKED ISSUE #1: wire in SFTP to Sheridan on publish
When hitting the "publish" link it should send this back automatically and change the status.

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1 

- [x] get passphrase from the environment
- [x] confirm sftp works
- [x] pass in only xml file to transfer
- [x] move to a "Sheridan" service
- [ ] confirm the "published" label
- [ ] add a published query?

### CODE REVIEW

**Comment by nickstiffler** [comment]
Now requires the env variable `SFTP_SECRET`. This can be put into your intellij run config or like this `SFTP_SECRET=sdfsdf grails run-app`. I am not sure where to put it in production though.

**Comment by nathandunn** [comment]
:+1  So far so good!

**Comment by nickstiffler** [comment]
This seems to be working. The pub status is updated to `Pub approved` in the UI, but is there additional feedback needed to show that the file was uploaded?

**Comment by nathandunn** [comment]
Yes.  Let’s push this to production (I can or you can).  Antony (on the other email thread) will be the guy to verify this. 

Merge and update (or have me update) and lets’ test it. 

Nathan

**Pull request merged**
