### PR TITLE
Dealing with XML comments

### PR DESCRIPTION
**Pull request by nickstiffler**
A bunch more fixes for the latest round. I clicked on "Reformat Code" in IntelliJ, so most of this is from that. You will need to revert/link for this to work.

### CODE REVIEW

**Comment by nathandunn** [comment]
Note:  `?w=1` ignores the white space:

     https://github.com/bioentity/Bioentity.link/pull/15/files?w=1

**Comment by nathandunn** [comment]
Looks good to me.   I'm happy to test whenver you get it in there.

**Comment by nickstiffler** [comment]
Ok, I will upload it now.

**Comment by nickstiffler** [comment]
It is up there now.

**Comment by nathandunn** [comment]
@nickstiffler  So far so good . . . going to run through her email and the SFTP stuff.

**Comment by nickstiffler** [comment]
Thanks. This PR mainly addresses issues noted by Deb:
- the DOCTYPE so it is from the original document
- handles the XML comment
- removes the xmlns attribute from list elements
- removes the extra caption end tag.

**Pull request merged**
